### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Xses-1** [Marcel1202/HTMLWallpaper#14]
It was working and displaying Javascript, I think I was using this:

`pip install PyQt5`
`pip install PyQtWebEngine`

I did:
`sudo apt install  qml-module-qtwebengine`

It fucked Plasma. 
`This application failed to start because it could not find or load the Qt platform plugin "xcb".`

I purged it, but it apparently changed lots of repos, but `sudo apt update` and `pkcon update` fixed that.

I installed it again and it didn't break everything now:
`sudo apt install qml-module-qtwebengine`

I also did:
`sudo apt install qml-module-qtwebkit`
 `sudo apt install qt5-default
`
But all I am getting is a black screen.

As soon as I touch this, I am back to xcb error:
`sudo apt purge qml-module-qtwebview`

I am using KDE Neon, btw.

**Comment by Xses-1** [comment]
Ok, I found the fix.

HTMLWallpaper apparently will not work without Plasma Addons. This is a package that contains a few useful features for the system tray, like a Caps notifier, or night mode switch. I couldn't find the name of it on Debian, so I asked on Reddit and after installing it HTMLWallpaper started to work.

Package name:
Arch - `kdeplasma-addons`
Debian - `plasma-widgets-addons`

I think it's worth to mention that in KDE Store.

**Comment by Marcel1202** [comment]
Hi, thanks for your report. I have added the requirement to the KDE store.
