### ISSUE TITLE
Works great as a wallpaper but doesn't render java script when set as lock screen.

### ISSUE THREAD

**Issue by akeyx** [Marcel1202/HTMLWallpaper#15]
Hi,
When setting this plugin as the Screen Locking "Wallpaper type" and providing a URL that would otherwise render content with Java script the javascript bit doesn't render.
Example URL: `https://rezmason.github.io/matrix/?skipIntro=false`

Error observed in the journal:
```
Dec 02 14:44:46 darkstar kscreenlocker_greet[23808]: js: Uncaught (in promise) TypeError: Cannot read property 'getExtension' of null
Dec 02 14:44:46 darkstar kscreenlocker_greet[23808]: js: Uncaught (in promise) TypeError: Cannot read property 'getExtension' of null
```

Would it be possible to fix this?

**Comment by gnoumph** [comment]
Works fine for me:

![image](https://user-images.githubusercontent.com/49097358/205321502-c820b099-270b-4fa1-a5a0-943645b32923.png)

Using Manjaro Linux 22.0.0 (kernel 6.0.8-1) and KDE Plasma 5.26.3 / KDE Frameworks 5.99.0 / Qt 5.15.7 on X11.

**Comment by akeyx** [comment]
Yeah , this is running in the normal wallpaper paper - admittingly that's main purpose of the plugin. So yes it does work fine here.
However, this plugin can also be chosen as the backend for Plasma's Lock screen:  System Settings -> Workspace Behavior -> Screen Locking -> Appearance (Configure button) -> Wallpaper type -> HTMLWallpaper

When applied and the screen is locked the errors I provided earlier appear and the page doesn't render.

**Comment by akeyx** [comment]
I'm using this in Fedora KDE Plasma 37.

**Comment by gnoumph** [comment]
Oh didn't know we can do that!  
And got the same issue.

**Comment by Marcel1202** [comment]
Using the plugin for lock screen is not one of the supported use-cases right now, as it always caused crashes on my machine. #6 tracks this feature request. I'll have another look at this, when considering a Plasma 6 version.
