### ISSUE TITLE
trouble getting videos to autoplay with sound

### ISSUE THREAD

**Issue by sh3zb0t** [Marcel1202/HTMLWallpaper#16]
according to mozilla documentation it needs to be explicitly allowed in browser but can't seem to find a config in the pling installation

**Comment by Marcel1202** [comment]
I believe this should be relatively easy to fix. What website did you want to get autoplay running on, so I can test it?

**Comment by sh3zb0t** [comment]
It's a local site with any hearable media with autoplay tag, doesn't matter if it's a video or audio
The behaviour is in par with mozilla documentation as it won't autostart if it plays audio unless theres a specified flag in the browser

**Comment by Marcel1202** [comment]
Fixed in https://github.com/Marcel1202/HTMLWallpaper/commit/593955818233c682b9696c2613b8174fa345fef7. Update your plugin to version 2.2 to get the changes.
