### ISSUE TITLE
Where does HTMLWallpaper save pages?

### ISSUE THREAD

**Issue by TabForce** [Marcel1202/HTMLWallpaper#17]
thank you for HTMLWallpaper - it's doing a great job showing my nextcloud account on my desktop.

I've saved the webpage by right-click "save page" on disk - now HTMLWallpaper shows a icon of the saved page on my desktop. Where can I find (and delete) that saved page? Reinstalling HTMLWallpaper doesn't help. Even deleting qtwebengine related files in my home partition doesn't help

please help
Ray

**Comment by Marcel1202** [comment]
I would assume it is saved in/home/yourusername/desktop if it shows up on the desktop, no?

**Comment by TabForce** [comment]
thank you for your fast reply!
~/Desktop was empty
but somehow it looks like I've created a widget (link to the page I'm using in HTMLWallpaper). I don't know how though.
Well, I could delete it from desktop as any other widget.
