### ISSUE TITLE
Can't open HTTPS URL with self-signed certificate

### ISSUE THREAD

**Issue by gnoumph** [Marcel1202/HTMLWallpaper#19]
It is not possible to open an HTTPS URL with a self-signed certificate.
A blank page is displayed with the error `ERR_CERT_AUTHORITY_INVALID`, and it is not possible to authorize the certificate as in a conventional browser.

Is there a solution to this problem?

Thanks :)

**Comment by Marcel1202** [comment]
912b75a89d6e7d77e0e65fd594cd5ddda3be11f1 adds ignoring HTTPS certificate errors as a configuration option.
