### ISSUE TITLE
Weißes Fenster unter KDE mit Wayland bei start

### ISSUE THREAD

**Issue by lugau45** [Marcel1202/HTMLWallpaper#21]
Wenn ich Wayland verwende kommt beim anmelden ein weißes Fenster, dann muss man immer manuell auf Bild stellen und dann zurück auf html dann geht es. Mit x geht alles.

**Comment by Marcel1202** [comment]
Plugin Version 2.3 wurde gerade für KDE Plasma 6 released, welches auf Wayland als Standard baut. Wenn in dieser Version das Problem immer noch auftritt, bitte das Issue wieder öffnen.
