### ISSUE TITLE
Any way to make a video go full screen?

### ISSUE THREAD

**Issue by linlinxza** [Marcel1202/HTMLWallpaper#23]
Finally, I found something that will possibly work for video backgrounds! But I am having an issue with making a video go full screen.

I whipped up something quick with HTML:

```
<!DOCTYPE html>
<html>
<body>
<video autoplay muted loop>
  <source src="vid.mp4" type="video/mp4">
</video>

</body>
</html>
```

I am wondering how I could make it go full screen to fill in the entire desktop background.

**Comment by Marcel1202** [comment]
Unfortunately, I can't provide support on how to write HTML. If this is an issue of this plugin specifically, i.e. it works in other browsers, please reply and I will re-open the issue.

**Comment by linlinxza** [comment]
Well, I really don't need the HTML file. I can put in the location of the video into this plugin and it will play. But is there a way you can make it fill the screen, hide the player controls and go on a loop? 

Here's an example what I can do with your plug with a video file:


https://github.com/Marcel1202/HTMLWallpaper/assets/11242593/b738eb0f-b263-449f-8118-424ccb0ed646

**Comment by Marcel1202** [comment]
The code I provided correctly filled the full screen of my VM (except for an annoying scroll bar on the right). I assume it has to do with the video not being the same aspect ratio as your screen, so I'd look into if it's possible to stretch a video in HTML.
