### ISSUE TITLE
Plugin doesn't handle left click events

### ISSUE THREAD

**Issue by Marcel1202** [Marcel1202/HTMLWallpaper#4]
Ever since a plasma update in November/December left click events are no longer registered by the plugin. Testing with code from the QML docs has shown that the events aren't even sent to any wallpaper plugin, so I assume this is an upstream bug of plasma.

**Comment by Marcel1202** [comment]
The bug has been filed on the KDE Bugtracking System. It can be found here: https://bugs.kde.org/show_bug.cgi?id=423217

**Comment by Michael-Z-Freeman** [comment]
Is there a workaround for this at the moment or at least a way to develop for this addon in the meantime ? For example I am finding something like the "plasmawallpaperviewer" that used to be used for development and now seems to be deprecated. Now it's plasma-sdk that was supposed to have replaced plasmamate that has ability to preview wallpaper plugins. However having installed the package I find no IDE or way of doing this. What am missing here ?

**Comment by redbrain** [comment]
The bug report specifies that the event is not handled in desktop-view, would it still work in folder-view?

**Comment by Marcel1202** [comment]
@redbrain No it doesn’t, but in Folder-View this is intended behavior and thus not a bug.

**Comment by Marcel1202** [comment]
@Michael-Z-Freeman Sorry for taking so long to reply. Using a virtual machine running Kubuntu 19.10 or earlier would be an option.

**Comment by redbrain** [comment]
Verified this on Plasma 5.20-2 on Arch, added a reply on the bugtracker to hopefully bump the attention.

**Comment by gnoumph** [comment]
Same as @redbrain, issue still there on Manjaro with KDE 5.25.5. Also added a reply on bugtracker :crossed_fingers:

**Comment by gnoumph** [comment]
Problem finally solved by Plasma 5.26!

**Comment by Michael-Z-Freeman** [comment]
Finally. Well thank you to who ever did that :)

**Comment by Marcel1202** [comment]
Fixed upstream
