### ISSUE TITLE
No URL field visible

### ISSUE THREAD

**Issue by Innercode** [Marcel1202/HTMLWallpaper#5]
Hi,

Installed the plugin version 2 in Kubuntu 20.04. There is no URL setting field visible in the Desktop Folder Settings window.

![image](https://user-images.githubusercontent.com/8807627/81805277-d98ff500-951a-11ea-99ac-dc440448dce1.png)

Thanks in advance

**Comment by Marcel1202** [comment]
Hi, please download version 2.1 and report back whether the issue persists. Thank you.

**Comment by Innercode** [comment]
@Marcel1202 That was it! Thanks
