### ISSUE TITLE
Module doesn't launch

### ISSUE THREAD

**Issue by Minabsapi** [Marcel1202/HTMLWallpaper#9]
**OS:** Ubuntu 20.04

As asked in the install instruction, I installed Qt5 WebEngine for my distribution, installed the module through the wallpaper module installer and logged out.

When I logged in back again inputing Alt+S+D did nothing, and launching the desktop configuration file "HTML Wallpaper" located in `~/.local/share/plasma/wallpapers/de.unkn0wn.htmlwallpaper` displays a dialog box "Error launching the application"

What could be the problem here ?

**Comment by Marcel1202** [comment]
Hey,
as HTMLWallpaper isn't a full application, running it by launching the metadata desktop file doesn't work.
After installing the HTMLWallpaper plugin it can be selected in the KDE Plasma Wallpaper menu.
You can access it by right clicking on your desktop and selecting the option at the very bottom, "Configure Desktop".
You should find HTMLWallpaper in the drop down menu "Wallpaper Type".
Please report back whether this resolved your issue.

**Comment by Minabsapi** [comment]
Found the option, thank you very much !
